apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .app_name }}-config
  namespace: {{ .namespace }}
  labels:
    app: {{ .app_name }}
data:
{{- range $key, $value := .config_data }}
  {{ $key }}: "{{ $value }}"
{{- end }}
