apiVersion: v1
kind: Service
metadata:
  name: {{ .app_name }}
  namespace: {{ .namespace }}
  labels:
    app: {{ .app_name }}
spec:
  type: {{ .service_type }}
  selector:
    app: {{ .app_name }}
  ports:
  - port: {{ .port }}
    targetPort: {{ .target_port }}
    protocol: {{ .protocol }}
    name: http
{{- if eq .service_type "NodePort" }}
  sessionAffinity: ClientIP
{{- end }}
